---
- name: Check if yay is installed
  command: which yay
  register: yay_check
  ignore_errors: yes
  become_user: "{{ user }}"

- name: Clone yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    force: yes
  become_user: "{{ user }}"
  when: yay_check.rc != 0

- name: Build and install yay
  shell: |
    cd /tmp/yay
    makepkg -si --noconfirm
  become_user: "{{ user }}"
  when: yay_check.rc != 0

- name: Clean up yay build directory
  file:
    path: /tmp/yay
    state: absent
  when: yay_check.rc != 0