# Hypridle config

general {
    lock_cmd = pidof hyprlock || hyprlock --grace 0 --immediate-render --no-fade-in
    on_lock_cmd = dunstctl set-paused true
    on_unlock_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'; dunstctl set-paused false
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprlock --grace 0 --immediate-render --no-fade-in
}

listener {
    timeout = 305
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# Workaround for post-lock display-off, including manual Mod+Escape lock: https://github.com/hyprwm/hypridle/issues/189
listener {
    timeout = 5
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
    ignore_inhibit = true
}
