set-option -g default-terminal "tmux-256color"

set-option -g status-style bg=default,fg=white
set-option -g window-style bg=default
set-option -g window-active-style bg=default

set-option -g status-left "[#S]: "
set-option -g status-left-style bg=#000000,fg=grey,bold
set-option -g status-left-length 50

set-option -g window-status-format " #I:#W#{?window_zoomed_flag, [Z], }"
set-option -g window-status-style bg=black,fg=grey

set-option -g window-status-current-format " #I:#W#{?window_zoomed_flag, [Z], }"
set-option -g window-status-current-style bg=green,fg=black,bold

set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g detach-on-destroy off
set-option -g history-limit 50000
set-option -g renumber-windows on

unbind -a
set -g prefix C-b
bind-key C-b send-prefix

bind-key ? list-keys
bind-key d detach-client
bind-key : command-prompt
bind-key q display-panes

unbind .
bind-key > swap-window -t +1 \; select-window -n
bind-key < swap-window -t -1 \; select-window -p

bind z resize-pane -Z
bind-key s choose-tree -s
bind c new-window

bind-key \{ swap-pane -U
bind-key \} swap-pane -D

bind-key r command-prompt "rename-session '%%'"
bind-key , command-prompt "rename-window '%%'"
bind-key R source-file ~/.tmux.conf; display "Refreshed!"

# https://unix.stackexchange.com/a/25638
# Prevent vim escape key delay
set -g escape-time 0

bind-key b copy-mode
bind-key v paste-buffer

bind-key x kill-pane
bind-key O kill-pane -a
bind-key w kill-window
bind-key W kill-session

setw -g mode-keys vi
setw -g mouse on

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel

# bind 'M-,' and 'M-.' to switch windows
bind-key -n M-, select-window -p
bind-key -n M-. select-window -n

# bind 'M-[' and 'M-]' to switch sessions
bind-key -n M-[ switch-client -p
bind-key -n M-] switch-client -n

# Bind 'Prefix + [1-6]' to switch panes
bind-key 1 select-pane -t 1
bind-key 2 select-pane -t 2
bind-key 3 select-pane -t 3
bind-key 4 select-pane -t 4
bind-key 5 select-pane -t 5
bind-key 6 select-pane -t 6

# Bind 'Prefix + Shift + [1-4]' to select-windows
bind-key ! select-window -t 1
bind-key @ select-window -t 2
bind-key \# select-window -t 3
bind-key $ select-window -t 4

# Bind 'Prefix + e' to split window vertically
bind-key e split-window -h
# Bind 'Prefix + o' to split window horizontally
bind-key o split-window -v

# Bind 'Ctrl + Alt + <h/j/k/l>' to resize panes (Prioritizing tmux panes)
bind-key -n C-M-h resize-pane -L 4
bind-key -n C-M-j resize-pane -D 4
bind-key -n C-M-k resize-pane -U 4
bind-key -n C-M-l resize-pane -R 4

# Bind 'Ctrl + <h/j/k/l>' to move between panes (Prioritizing Neovim panes)
bind-key -n C-h run-shell 'pstree -p $(tmux display-message -p "#{pane_pid}") | rg -q "nvim" && tmux send-keys C-h || tmux select-pane -L'
bind-key -n C-j run-shell 'pstree -p $(tmux display-message -p "#{pane_pid}") | rg -q "nvim" && tmux send-keys C-j || tmux select-pane -D'
bind-key -n C-k run-shell 'pstree -p $(tmux display-message -p "#{pane_pid}") | rg -q "nvim" && tmux send-keys C-k || tmux select-pane -U'
bind-key -n C-l run-shell 'pstree -p $(tmux display-message -p "#{pane_pid}") | rg -q "nvim" && tmux send-keys C-l || tmux select-pane -R'

set -g @plugin 'tmux-plugins/tmux-resurrect'

# tmux-session-wizard.
set -g @plugin '27medkamal/tmux-session-wizard'
# Press 'Prefix + p' to open the session wizard
# The wizard lists existing sessions followed by recently accessed directories (using zoxide)
set -g @session-wizard 'p'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
