WORDCHARS='*?[]~=\@.:; -_&;!#$%^(){}<>/|'

fpath=($ZDOTDIR/zsh-completions/src $fpath)
autoload -U +X bashcompinit && bashcompinit
autoload -Uz compinit
compinit -C

zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' menu no

setopt NO_CASE_GLOB
setopt NO_CASE_MATCH
zstyle ':completion:*' completer _complete _approximate
zstyle ':completion:*:approximate:*' max-errors 1 numeric

zstyle ':completion:*' matcher-list '' \
        'm:{a-z\-}={A-Z\_}' \
        'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
        'r:|?=** m:{a-z\-}={A-Z\_}'

zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'l' vi-forward-char
bindkey -a "k" .up-line-or-history
bindkey -a "j" .down-line-or-history

bindkey -M menuselect '\e' send-break
bindkey -M menuselect '^N' down-line-or-history
bindkey -M menuselect '^P' up-line-or-history

function vi-history-up-and-highlight() {
        zle vi-up-line-or-history
        zle end-of-line
}
zle -N vi-history-up-and-highlight

function vi-history-down-and-highlight() {
        zle vi-down-line-or-history
        zle end-of-line
}
zle -N vi-history-down-and-highlight

bindkey -M vicmd 'k' vi-history-up-and-highlight
bindkey -M vicmd 'j' vi-history-down-and-highlight

KEYTIMEOUT=1

setopt AUTO_CD
setopt AUTO_PUSHD
setopt AUTO_MENU
setopt ALWAYS_TO_END
setopt AUTO_PARAM_SLASH
setopt LIST_PACKED
setopt EXTENDEDGLOB
setopt NOTIFY
setopt NOMATCH
setopt INTERACTIVE_COMMENTS

HISTFILE=$ZDOTDIR/zsh_history
HISTSIZE=999999999
SAVEHIST=$HISTSIZE
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt SHARE_HISTORY             # Share history between all sessions (implies APPEND_HISTORY and INC_APPEND_HISTORY).
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.

unsetopt BEEP

ZSH_AUTOSUGGEST_STRATEGY=(history completion match_prev_cmd)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=100

source $ZDOTDIR/zsh-autosuggestions/zsh-autosuggestions.zsh
source $ZDOTDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source <(fzf --zsh)
export FZF_DEFAULT_COMMAND='fd --hidden --color=always'
export FZF_DEFAULT_OPTS="--ansi ${FZF_DEFAULT_OPTS} --multi --cycle --tiebreak=length,begin,end"
export FZF_DEFAULT_OPTS="--bind='ctrl-y:accept,ctrl-a:select-all,ctrl-d:deselect-all' ${FZF_DEFAULT_OPTS}"
export FZF_PREVIEW_FILE_CMD='bat --color=always --style=numbers --line-range=:500'

bindkey -a '\er' fzf-history-widget
bindkey '\er' fzf-history-widget

source $ZDOTDIR/fzf-tab/fzf-tab.plugin.zsh
# zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' use-fzf-default-opts yes

bindkey '\eo' vi-forward-word
bindkey '^O' autosuggest-accept

bindkey -M viins '^N' fzf-tab-complete
bindkey -M viins '^P' fzf-tab-complete

# stop word deletion at word boundaries
backward-kill-word-strict() {
	local wordchars="$WORDCHARS"
	local i=${#LBUFFER}
	local first=true
	local delete_space=false

	while ((i > 0)); do
		local c="${LBUFFER[i]}"
		if [[ "$c" == " " ]]; then
			if [[ "$first" == true ]]; then
				delete_space=true
			elif [[ "$delete_space" != true ]]; then
				break
			fi
		else
			if [[ "$delete_space" == true ]]; then
				break
			fi
			delete_space=false
		fi

		if [[ "$first" == true || "$wordchars" != *"$c"* || (("$delete_space" == true && "$c" == " ")) ]]; then
			((i--))
		else
			break
		fi
		first=false
	done
	LBUFFER="${LBUFFER[1, i]}"
}
zle -N backward-kill-word-strict

bindkey '^W' backward-kill-word-strict
bindkey '^?' backward-delete-char
bindkey '^H' backward-delete-char
bindkey '^U' backward-kill-line

[[ -f $ZDOTDIR/zsh_functions ]] && source $ZDOTDIR/zsh_functions

#################################################################################

alias ls='ls --color=always'
alias kc="kubectl"
alias tf="terraform"

PATH=$PATH:$HOME/.local/bin

export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/.local/share/coursier/bin:$PATH

if command -v nvim >/dev/null; then
        export EDITOR='nvim -f'
        export KUBE_EDITOR='nvim -f'
        export MANPAGER="nvim +Man!"
elif command -v bat >/dev/null; then
        export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

if command -v golangci-lint >/dev/null; then
        source <(golangci-lint completion zsh)
fi
if command -v dlv >/dev/null; then
        source <(dlv completion zsh)
fi
if command -v kubectl >/dev/null; then
        source <(kubectl completion zsh)
fi
if command -v terraform >/dev/null; then
        complete -o nospace -C $(which terraform) terraform
fi
if command -v helm >/dev/null; then
        source <(helm completion zsh)
fi

if command -v zoxide >/dev/null; then
        alias cd='z'
        eval "$(zoxide init zsh)"
else
        echo "zoxide not found"
fi

eval "$(starship init zsh)"
